name: CI

on: [push]

jobs:
  build:
    strategy:
      max-parallel: 15
      matrix:
        # TODO : enable tests on windows
        operating-system: [ubuntu-latest, macOS-latest]
        php-versions: ['7.2', '7.3', '7.4']

    name: PHP ${{ matrix.php-versions }} Test on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}

    steps:
    - uses: actions/checkout@v1

    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: ${{ matrix.php-versions }}
        extension-csv: mbstring, dom

    - name: Get Composer Cache Directory
      id: composer-cache
      run: echo "::set-output name=dir::$(composer config cache-files-dir)"

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache vendor
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: composer run-script test

  sonarcloud:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
    - uses: actions/checkout@v1
    - name: Setup PHP
      uses: shivammathur/setup-php@master
      with:
        php-version: 7.4
        extension-csv: mbstring, xdebug, dom
        coverage: xdebug

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: composer run-script test -- --coverage-clover=coverage.clover

    - run: wget https://scrutinizer-ci.com/ocular.phar
    - name: Upload code coverage
      run: php ocular.phar code-coverage:upload --format=php-clover coverage.clover